### ISSUE TITLE
更新计划

### ISSUE THREAD

**Issue by greenhat616** [hitokoto-osc/reviewer-frontend#102]
## 等待上游完成 Vue 3 支持
* [x] Vue.js 3 (RC)
* [x] Nuxt.js, currently in closed source beta
* [x] Ant Design Vue, currently in beta

----
上游 Issue 堵塞：
https://github.com/vueComponent/ant-design-vue/issues/6888 - 暂时通过全局 Message API 解决
https://github.com/nuxt/devtools/issues/402 - 无伤大雅

**Comment by kecrily** [comment]
Today Nuxt.js 3 had came to beta.

See https://v3.nuxtjs.org
